### ISSUE TITLE
Suggestion: during .jar download, show message in minibuffer.

### ISSUE THREAD

**Issue by daveloyall** [cosmicexplorer/speech-tagger#2]
Suggestion: during the download of the .jar file, you should show a meaningful message in minibuffer, so that users don't terminate the command.

Cheers,
--Dave

**Comment by cosmicexplorer** [comment]
Good idea. Back when I first wrote this I didn't know about `cl-letf`. This information is in the readme, but it's probably at least a little helpful to see it here too. Ideally I'd do the downloading asynchronously with a cute little progress bar, but since the download happens very rarely this works.

**Comment by daveloyall** [comment]
Cool, thanks!
